# Generated by Django 4.2.4 on 2023-09-02 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('quantity_mn', models.IntegerField(blank=True, default=0, null=True)),
                ('packing', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity_kg', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('total_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('price_40kg', models.IntegerField(blank=True, default=0, null=True)),
                ('amount', models.DateTimeField(auto_now_add=True)),
                ('loss', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('loss_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('net_amount', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seeds.seed')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='seeds.customer')),
            ],
        ),
    ]
