# Generated by Django 4.2.4 on 2023-09-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0002_alter_purchase_amount_alter_purchase_loss_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='loss_kg',
        ),
        migrations.AddField(
            model_name='purchase',
            name='left_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vehicle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
