# Generated by Django 4.2.4 on 2023-09-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0004_alter_purchase_packing_alter_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='loss_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
