# Generated by Django 4.2.4 on 2023-09-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0005_purchase_loss_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
