# Generated by Django 4.0.3 on 2023-10-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0009_feed_rent_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='totalKg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
